clients = ["AMPDeviceDiscoveryAgent","Safari","SpringBoard","accountsd","atwakeup","backupd"]
[lockdownd_domains.com.apple.Accessibility]
properties = ["ClosedCaptioningEnabledByiTunes","InvertDisplayEnabledByiTunes","MonoAudioEnabledByiTunes","SpeakAutoCorrectionsEnabledByiTunes","VoiceOverTouchEnabledByiTunes","ZoomTouchEnabledByiTunes"]
[lockdownd_domains.com.apple.mobile.backup]
properties = ["CloudBackupEnabled","LastCloudBackupDate","LastCloudBackupTZ","WillEncrypt"]
[lockdownd_domains.com.apple.mobile.restriction]
properties = ["ClosedCaptioningEnabledByiTunes","CloudBackupEnabled","DeveloperStatus","EnableWifiConnections","EnableWifiDebugging","InvertDisplayEnabledByiTunes","LastCloudBackupDate","LastCloudBackupTZ","MonoAudioEnabledByiTunes","Notes","ProhibitAppDelete","ProhibitAppInstall","RestoreState","SetupState","SpeakAutoCorrectionsEnabledByiTunes","VoiceOverTouchEnabledByiTunes","WillEncrypt","ZoomTouchEnabledByiTunes"]
[lockdownd_domains.com.apple.mobile.tethered_sync]
properties = ["Notes"]
[lockdownd_domains.com.apple.mobile.wireless_lockdown]
properties = ["EnableWifiConnections","EnableWifiDebugging"]
[lockdownd_domains.com.apple.purplebuddy]
properties = ["RestoreState","SetupState"]
[lockdownd_domains.com.apple.xcode.developerdomain]
properties = ["DeveloperStatus"]
[metadata]
credits = ["rickmark"]
description = "Services that can be contacted over usbmuxd via lockdownd"