name: Publish Package - Ruby RubyGems

on:
  push:
    branches: [ main ]

jobs:
  ci-build-ruby:
    uses: hack-different/apple-knowledge/.github/workflows/build-ruby.yml@main

  publish-gem:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    needs: ci-build-ruby
    environment: gem-push
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - uses: actions/download-artifact@v3
        name: Download Ruby Package Artifacts
        with:
          name: package-gem-3.2

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
